namespace NeoModules.RPC
{
	public enum ApiMethods
	{
		getaccountstate,
        getapplicationlog,
		getassetstate,
		getbalance,
		getbestblockhash,
		getblock,
		getblockcount,
		getblocksysfee,
		getblockhash,
		getconnectioncount,
		getcontractstate,
		getrawmempool,
		getrawtransaction,
		getstorage,
		gettxout,
		getversion,
		invoke,
		invokefunction,
		invokescript,
		sendrawtransaction,
		sendtoaddress,
		sendfrom,
		sendmany,
		getnewaddress,
        listaddress,
		dumpprivkey,
		validateaddress,
		getpeers,
	}
}
