namespace NeoModules.RPC
{
    public enum ApiMethods
    {
        getaccountstate,
        getapplicationlog,
        getassetstate,
        getbalance,
        getbestblockhash,
        getblock,
        getblockcount,
        getblockheader,
        getblocksysfee,
        getblockhash,
        getconnectioncount,
        getcontractstate,
        getrawmempool,
        getrawtransaction,
        getstorage,
        gettxout,
        getvalidators,
        getversion,
        getwalletheight,
        invoke,
        invokefunction,
        invokescript,
        sendrawtransaction,
        sendtoaddress,
        sendfrom,
        sendmany,
        getnewaddress,
        listaddress,
        dumpprivkey,
        validateaddress,
        getpeers
    }
}